export default {
  'tencent-map': [
    'idle',
    'tilesloaded',
    'click',
    'rightclick',
    'dblclick',
    'mousedown',
    'mouseup',
    'mousemove',
    'touchstart',
    'touchmove',
    'touchend',
    'dragstart',
    'drag',
    'dragend',
    'panstart',
    'pan',
    'panend',
    'rotatestart',
    'rotate',
    'rotateend',
    'pitchstart',
    'pitch',
    'pitchend',
    'zoom',
    'resize',
    'center_changed',
    'bounds_changed',
    'scale_changed',
    'control_added',
    'control_removed',
    'animation_playing',
    'animation_looped',
    'animation_ended',
    'animation_stopped',
  ],
  'tencent-marker': [
    'click',
    'dblclick',
    'mousedown',
    'mouseup',
    'mouseout',
    'mouseover',
    'hover',
    'moving',
    'move_ended',
    'move_stopped',
    'move_paused',
    'move_resumed',
  ],
  'tencent-label': [
    'click',
    'dblclick',
    'mousedown',
    'mouseup',
    'mouseover',
    'mousemove',
    'hover',
  ],
  'bm-polyline': [
    'click',
    'dblclick',
    'mousedown',
    'mouseup',
    'mouseout',
    'mouseover',
    'remove',
    'lineupdate'
  ],
  'bm-polygon': [
    'click',
    'dblclick',
    'mousedown',
    'mouseup',
    'mouseout',
    'mouseover',
    'remove',
    'lineupdate'
  ],
  'bm-circle': [
    'click',
    'dblclick',
    'mousedown',
    'mouseup',
    'mouseout',
    'mouseover',
    'remove',
    'lineupdate'
  ],
  'bm-label': [
    'click',
    'dblclick',
    'mousedown',
    'mouseup',
    'mouseout',
    'mouseover',
    'remove',
    'rightclick'
  ],
  'bm-info-window': [
    'close',
    'open',
    'maximize',
    'restore',
    'clickclose'
  ],
  'bm-ground': [
    'click',
    'dblclick'
  ],
  'bm-autocomplete': [
    'onconfirm',
    'onhighlight'
  ],
  'bm-point-collection': [
    'click',
    'mouseover',
    'mouseout'
  ]
}
